### ISSUE TITLE
Hardware Setup

### ISSUE THREAD

**Issue by Bouni** [raintonr/hormann-hcp#2]
Hi,

as you sucessfully communicated with the motor (#1) would you give a bit more information on your setup?
Also, do you plan on building some kind of ESP32 device that interfaces with the Hormann drives?

**Comment by raintonr** [comment]
Experiments so far are just using my laptop with a cheap USB RS485 dongle, like this:

![image](https://user-images.githubusercontent.com/3794098/107614648-06f50500-6c4b-11eb-9bfe-8371a89ae680.png)

I am currently experimenting with control of a LineaMatic P gate motor. We have a Loxone system here and there is cat7 cable to the gate installation location. I know the motor could be controlled via relays but that seems inelegant. I also like to tinker so wanted to use the HCP protocol if possible and share the experience so others could take advantage.

If this can be made to work then the cat7 cable can be used for IP network (rather than 'dumb' relay control of the gate) and I can install an SBC (Raspberry Pi, etc) to control the  gate (and other lights/sensors) and other IP devices (an IP intercom for example) in that location.

If this can be made to work reliably from a Linux box with USB dongle then I will create an ioBroker adapter for HCP as I like ioBroker.

If if turns out commands are unreliable (to early to tell) then will have to add an MCU to do software serial and have that talk to an SBC over a second, regular serial line. This seems wasteful though and would like to avoid that if possible.

**Comment by Bouni** [comment]
OK, so that seem sto be an off the shelf USB to RS485 converter.
I guess that means that using an ESP32 + MAX485 will do the Trick as well.
Using your Baudrate switching Trick to get the syncbreak could completely eliminate the need for the soft serial!
And the Hardware UARTS are genarally more reliable and easier to use than the soft serial implementations.

**Comment by raintonr** [comment]
> If this can be made to work reliably from a Linux box with USB dongle...

Well, the code as of now seems to function flawlessly :)

I press 1/2/3 on keyboard and the motor instantly responds. It doesn't seem to skip commands or have any issues so pretty happy with that! Next step, will test that this works on an SBC (#3).
